feat: t-6 get only dirs of the files
dmitrymaslov13/devops-camp-2023 pull request #10
Opened 2023-04-03 19:06 UTC by dmitrymaslov13

# Summary

## Test Task
Script should get a folder as an argument and return a list of unique directories of all files (including in the nested directories).
only `-f` option is allowed for the use of `find` command, i.e.:  `find /tmp -type f`. Which should find all files in all nested dirs and then process the output by using expansion.
**name the file:** `chapter2-l2-t6-get-file-unique-dirs.sh`
**example of the call:**
```sh
./chapter2-l2-t6-get-file-unique-dirs.sh ~/tmp
/tmp/setguid
/tmp/bazel/tools/objc
/tmp/bazel/third_party/zlib
/tmp/bazel/third_party/zlib/test
/tmp/bazel/third_party/zlib
/tmp/bazel/third_party/zlib/examples
/tmp/bazel/third_party/zlib
/tmp/bazel/third_party/zlib/contrib/untgz
/tmp/bazel/third_party/zlib/contrib/testzlib
/tmp/bazel/third_party/zlib/contrib/puff
```

## my results

```sh
❯ ./chapter2-l2-t6-get-file-unique-dirs.sh $SARITASA/devops-camp-2023 
```

**output**:
```sh
/home/dmitrym/Documents/Saritasa/devops-camp-2023
/home/dmitrym/Documents/Saritasa/devops-camp-2023/chapter2/tests/t6
/home/dmitrym/Documents/Saritasa/devops-camp-2023/chapter2/tests/t7
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/hooks
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.github
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/info
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/logs
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/logs/refs/heads
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/logs/refs/heads/feature
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/logs/refs/remotes/origin
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/logs/refs/remotes/origin/feature
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/02
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/03
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/08
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/09
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/0a
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/0b
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/0c
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/0d
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/0e
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/0f
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/11
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/12
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/14
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/17
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/18
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/19
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/1a
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/1c
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/1d
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/1e
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/20
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/22
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/23
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/24
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/26
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/27
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/28
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/2a
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/30
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/33
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/34
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/35
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/38
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/39
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/3b
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/3d
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/3e
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/44
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/46
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/48
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/49
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/4d
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/4e
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/4f
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/51
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/52
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/53
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/55
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/56
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/58
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/59
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/5b
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/5e
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/60
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/61
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/62
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/63
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/65
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/67
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/69
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/6b
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/6c
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/6d
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/6e
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/6f
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/70
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/73
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/75
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/76
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/77
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/78
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/79
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/7a
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/7c
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/7e
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/7f
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/82
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/85
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/86
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/88
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/8c
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/8d
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/8f
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/91
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/92
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/93
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/94
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/97
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/9a
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/a1
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/a3
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/a4
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/a7
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/ae
/home/dmitrym/Documents/Saritasa/devops-camp-2023/.git/objects/af
/home/dmitrym/Doc [...]

2023-04-11 10:21 UTC, kseniyashaydurova approved these changes

2023-04-11 10:21 UTC, kseniyashaydurova commented on chapter2/tests/t6/chapter2-l2-t6-get-file-unique-dirs.sh
> +done | sort -u
Please always add 1 empty line at the end of each script

2023-04-11 11:38 UTC, dmitrymaslov13 commented on chapter2/tests/t6/chapter2-l2-t6-get-file-unique-dirs.sh
> +done | sort -u
please tell me what is it for?

2023-04-26 06:50 UTC, roman-mightydevops requested changes
```
✗  ./chapter2-l2-t6-get-unique-files.sh /home/ginto 
find: ‘/home/ginto/Projects_trash/GB/zabbix-docker/zbx_env/var/lib/postgresql/data’: Permission denied
find: ‘/home/ginto/TEMP/camp/darliiin/devops-camp-2023/chapter2/tests/t4/2’: Permission denied
./test.sh: 6: readonly: to/.xsessio: bad variable name
```

Please, add some comments and input checks as in previous tasks:

    that at least 1 arg was passed
    that target directory exists and readable

2023-12-09 22:07 UTC, closed without merging