feat: t3 - find namespaces without the backup
dmitrymaslov13/devops-camp-2023 pull request #11
Opened 2023-04-04 06:57 UTC by dmitrymaslov13

# Summary

## Test Task
We need to come up with a prototype solution that will give us the list of kubernetes namespaces we haven't backed up.
We have a special backup manifest that contains the configurationf for the backups. 

**For example:**
https://gist.github.com/dmitry-mightydevops/016139747b6cefdc94160607f95ede74

the configuration is in the schedules.[].includedNamespaces block of the file

```yaml
        schedules:
          system:
            labels:
              backup: system
            schedule: "@every 24h"
            template:
              ttl: "480h"
              includedNamespaces:
                - cert-manager
                - ingress-nginx
                - kube-node-lease
                - kube-public
                - kube-system
                - ops
                - opsgenie
                - default
              excludedResources:
                - orders.acme.cert-manager.io
                - challenges.acme.cert-manager.io
                - certificaterequests.cert-manager.io
          a3fs:
            labels:
              backup: a3fs
            schedule: "@every 24h"
            template:
              ttl: "480h"
              includedNamespaces:
                - a3fs
```

we're supposed to run the following command:

`➜ kubectl get ns -o="custom-columns=NAME:.metadata.name" --no-headers` 

that will give us a list of all namespaces in the kubernetes cluster. 

The result of this command is https://gist.github.com/dmitry-mightydevops/297c4e235b61982f21a0bbbf7319ac24

Implement the bash script that will find all namespaces in the cluster that has not been configured in the velero manifest. I.e. operation on sets.

**name the file:** `chapter2-t3-velero-eks-diff.sh`

**nuances:**
- your bash script should download these 2 gists using curl and pass them into stdout of other commands you're using.
- you can use any CLI tool from the distro you're using to calculate the diff between two data blocks and come up with the output above.
- you can use `yq` or `jq` cli if necessary for your ops.

## my results

```sh
❯ ./chapter2-t3-velero-eks-diff.sh
```

**output**:
```sh
aacct
aaoa-ari-cleara
arthrexvip
axia
camp-dotnet
camp-python
camp-unity
caregiver
ci-experiments
ci-experiments-apps
commlrning
debug
demo
dev
disvr
dogvr
enrgy
fallon-medica
faroeve
fbmm
firearm
github-inactivity
igntpb
inkus
insights-agent
interesnee
jenkins
kubewatch
macroplate
mailhog
maunf
medvr
metrics-server
nrs
oprs
prfctpt
redis
rma
saritasa-android
saritasa-ios
saritasa-jira-qa-tool
saritasa-php
saritasa-python
saritasa-qa
saritasa-unity
scripta
sgvr
sportsthread
streetparking
tekton-pipelines-experiments
toro
tran
trapi
trivver
utd
utils
velero
vrcatchup
```

2023-04-04 10:39 UTC, kseniyashaydurova requested changes

2023-04-04 10:39 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +readonly BACKUP_MANIFEST_URL='https://gist.githubusercontent.com/dmitry-mightydevops/016139747b6cefdc94160607f95ede74/raw/030a82af2489bc353cec370779cfd06852668e29/velero.yaml'
1. Let's raise nice output when some of files are not found, now it is not clear what exactly was not found
![image](https://user-images.githubusercontent.com/26448672/229762641-f7491078-5b8e-4934-a9cb-1fd5ea9c36db.png)

2. also it is not user friendly to not show error in case if `velero.yaml` file not found and just print contents of `kubernetes-namespaces.txt`

2023-04-04 10:39 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +get_backup_manifest() {
Your `get_backup_manifest` and `get_kube_namespaces` do absolutely the same stuff, but with different vars. Please reorganize your code to DRY

2023-04-04 10:39 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +(
It doesn't look that your script makes correct diff, something doesn't work here
![image](https://user-images.githubusercontent.com/26448672/229765961-2f33ec9d-22a5-40c1-8b45-29b49fefa9da.png)

2023-04-04 10:39 UTC, kseniyashaydurova commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +  echo "${backup}"| yq ".spec.source.helm.values" -r | yq '.schedules[].template.includedNamespaces[]' -r
Why you have different quotes in one place and another? Let's follow one style)

2023-04-08 07:23 UTC, dmitrymaslov13 commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +get_backup_manifest() {
the idea was that we mimic the behavior of other console commands, but okay, this task is not big, and since the commands are used once, it really looks a bit redundant

2023-04-14 03:31 UTC, kseniyashaydurova approved these changes

2023-04-26 07:15 UTC, roman-mightydevops approved these changes

2023-04-26 07:15 UTC, roman-mightydevops commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +  local response_status=$(curl -I --silent "${url}" | head -n 1 | cut -d' ' -f2)
```suggestion
  local response_status
  response_status=$(curl -I --silent "${url}" | head -n 1 | cut -d' ' -f2)
```

https://unix.stackexchange.com/a/687856

2023-04-26 07:15 UTC, roman-mightydevops commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +comm -13 <( echo "${namespaces_from_backup}" | sort -u) <( echo "${kube_namespaces}" | sort -u)
You have 4 different ways of putting spaces around brackets in 4 lines, try to be consistent

2023-04-26 07:15 UTC, roman-mightydevops commented on chapter2/tests/t3/chapter2-t3-velero-eks-diff.sh
> +  echo "${backup}"| yq ".spec.source.helm.values" -r | yq ".schedules[].template.includedNamespaces[]" -r
```suggestion
  echo "${backup}" | yq ".spec.source.helm.values" -r | yq ".schedules[].template.includedNamespaces[]" -r
```

2023-04-29 17:21 UTC, merged