feat: t1 - existance of files
dmitrymaslov13/devops-camp-2023 pull request #2
Opened 2023-03-28 06:26 UTC by dmitrymaslov13

2023-03-29 04:11 UTC, kseniyashaydurova requested changes

2023-03-29 04:11 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +output=output
Please always add `#!/bin/bash` line in bash files

2023-03-29 04:11 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +  if [[ -e $1 ]]
So you work with only 1st argument only in this loop, 2d one is always ignored

2023-03-29 04:11 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +  echo $RANDOM | base64 > ${out}
Did you notice if you call below command few times in the console, it will give the same results most of times? I suggest you to find better command to prepare base64 random string, so it would be always unique

```
echo $RANDOM | base64
```

2023-03-29 04:11 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +# Show file content
Add docs what args function accepts

2023-03-30 06:43 UTC, roman-mightydevops requested changes
> write bash shell script that accepts two arguments with filenames.

Accepts any number of arguments now.

> script should verify if those files exists and if so - output the content of these files

Doesn't work.

2023-03-30 06:43 UTC, roman-mightydevops commented on chapter2/tests/t1/.gitignore
> +output/*
Put newline to get rid of this noisy error.

2023-03-30 06:43 UTC, roman-mightydevops commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +output=output
Constants should be all caps with underscores, also consider adding `readonly` to make it clear.
```suggestion
#Constants
readonly OUTPUT=output
```

2023-03-30 06:43 UTC, roman-mightydevops commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +mkdir -p ${output}
Don’t hide executable code between functions. If you’ve got functions, only includes, set statements and setting constants may be done before declaring functions.

2023-03-30 06:43 UTC, roman-mightydevops commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +  chmod 700 ${out}
Always quote strings containing variables.
```suggestion
  head -n 10 /dev/urandom | base64 > "${out}"
  chmod 700 "${out}"
```

2023-03-30 06:43 UTC, roman-mightydevops commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +  echo ===
It won't work because `=` is a meta-character. If you want string as it is, quote it with single quotes.
```suggestion
  echo '==='
```

2023-03-30 06:43 UTC, roman-mightydevops commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +done
Add newline.

2023-03-30 08:08 UTC, kseniyashaydurova commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +  echo ===
Also please use similar quotes within the file `"` or `'`

2023-03-30 08:09 UTC, kseniyashaydurova commented
@dmitrymaslov13 Also please don't resolve PR comments for us, PR reviewer should resolve it, if he sees that it was fixed (not you)

2023-04-03 02:42 UTC, roman-mightydevops requested changes

2023-04-03 02:42 UTC, roman-mightydevops commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +  echo "This script requires two arguments"
Why hardcode, when you have NUMBER_OF_ARGUMENTS constant? Now I might update constant value in the top of the file and forget to update this line.

2023-04-03 02:42 UTC, roman-mightydevops commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +for path in ${PATHS}; do
Doesn't work if my files names contain spaces:
```
ginto in on ginto-pc on ☸ teleport.saritasa.rocks-teleport.saritasa.rocks (github-arc) ~/TEMP/camp
➜ ls
chapter2-t1-two-files.sh

ginto in on ginto-pc on ☸ teleport.saritasa.rocks-teleport.saritasa.rocks (github-arc) ~/TEMP/camp
➜ ./chapter2-t1-two-files.sh 'my file' 'my second file'
my
=======================
very long string...
EOF

file
=======================
very long string...
EOF

ginto in on ginto-pc on ☸ teleport.saritasa.rocks-teleport.saritasa.rocks (github-arc) ~/TEMP/camp
➜ ls
chapter2-t1-two-files.sh  file  my  second
```

2023-04-03 02:43 UTC, kseniyashaydurova approved these changes

2023-04-03 02:43 UTC, kseniyashaydurova commented on chapter2/tests/t1/.gitignore
> +output/*
I think now this `.gitignore` is redundant, because you have no `output` folder

2023-04-03 17:33 UTC, dmitrymaslov13 commented on chapter2/tests/t1/chapter2-t1-two-files.sh
> +for path in ${PATHS}; do
I understand what you are talking about, thanks!

2023-04-26 06:23 UTC, roman-mightydevops approved these changes

2023-04-29 17:11 UTC, merged