feat: t2 - kustomization generator
dmitrymaslov13/devops-camp-2023 pull request #4
Opened 2023-03-28 18:00 UTC by dmitrymaslov13

# Summary

## Test Task

You need to have https://kustomize.io/ installed (part of your onboarding plan)

- write bash script that accepts unlimited number of arguments. 
- each argument means the name of the repository. 
- generate a valid `ed25519` ssh key for each of the repository. Store the keys in repos/ folder
  - each key should have the following suffix added to the file `-deploy-key.pem`, for example `iss-kubernetes-aws-deploy-key.pem`
- generate the `repos/kustomization.yaml` file based on the structure provided below
- make sure you can run cli `kustomize build repos` and get proper generated output without errors like this one: 
- validate for errors and don't allow execution if no args are passed to the script
- your script should perform `kustomize build repos` and output the yaml file to stdout

  ```yaml
  apiVersion: kustomize.config.k8s.io/v1beta1
  kind: Kustomization
  
  generatorOptions:
    disableNameSuffixHash: true
  
  secretGenerator:
    - name: iss-kubernetes-aws
      namespace: argo-cd
      options:
        labels:
          argocd.argoproj.io/secret-type: repository
      literals:
        - name=iss-kubernetes-aws
        - url=git@github.com:saritasa-nest/iss-kubernetes-aws.git
        - type=git
        - project=default
      files:
        - sshPrivateKey=iss-kubernetes-aws-deploy-key.pem
  
    - name: iss-backend
      namespace: argo-cd
      options:
        labels:
          argocd.argoproj.io/secret-type: repository
      literals:
        - name=iss-backend
        - url=git@github.com:saritasa-nest/iss-backend.git
        - type=git
        - project=default
      files:
        - sshPrivateKey=iss-backend-deploy-key.pem
    
    - name: iss-frontend
      namespace: argo-cd
      options:
        labels:
          argocd.argoproj.io/secret-type: repository
      literals:
        - name=iss-frontend
        - url=git@github.com:saritasa-nest/iss-frontend.git
        - type=git
        - project=default
      files:
        - sshPrivateKey=iss-frontend-deploy-key.pem
  ```

## my results

```sh
cd t2/
./chapter2-t2-gen-kustomization.sh iss-kubernetes-aws iss-backend iss-frontend
```

**output**:

```sh
➜  ./chapter2-t2-gen-kustomization.sh backend frontend desktop          
apiVersion: v1
data:
  name: YmFja2VuZA==
  project: ZGVmYXVsdA==
  sshPrivateKey: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdG
    RqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3Ra
    VwpReU5UVXhPUUFBQUNEUVYwK2tCSGN6eHIvN21FcW1tc2cweTlDMzFxV2FEVTRyekZ2Zl
    JQRVpBZ0FBQUtBR3N5VzNCck1sCnR3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDRFFWMCtr
    QkhjenhyLzdtRXFtbXNnMHk5QzMxcVdhRFU0cnpGdmZSUEVaQWcKQUFBRURTRDhNcTFFVV
    FMb2RacHlMV3AvZ0RNb1ozbUdxVzFRVis1KzlrVmUvTDR0QlhUNlFFZHpQR3YvdVlTcWFh
    eURUTAowTGZXcFpvTlRpdk1XOTlFOFJrQ0FBQUFGbVJ0YVhSeWVXMUFaRzFwZEhKNWN5MX
    NZWEIwYjNBQkFnTUVCUVlICi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=
  type: Z2l0
  url: Z2l0QGdpdGh1Yi5jb206c2FyaXRhc2EtbmVzdC9iYWNrZW5kLmdpdA==
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: backend
  namespace: argo-cd
type: Opaque
---
apiVersion: v1
data:
  name: ZGVza3RvcA==
  project: ZGVmYXVsdA==
  sshPrivateKey: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdG
    RqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3Ra
    VwpReU5UVXhPUUFBQUNCbUlpM3hENTU4aEtQNkVDamtuaGNZUmZRVkJQeU00V3ZaY3RoVj
    hqRzQwd0FBQUtCSUR1Y1dTQTduCkZnQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQm1JaTN4
    RDU1OGhLUDZFQ2prbmhjWVJmUVZCUHlNNFd2WmN0aFY4akc0MHcKQUFBRUI0WnpQZ2RDWV
    YxNGdpSzFJTEN2VG93WTl3cjJTQkE5Z0owaVRMUlE4S3BHWWlMZkVQbm55RW8vb1FLT1Nl
    RnhoRgo5QlVFL0l6aGE5bHkyRlh5TWJqVEFBQUFGbVJ0YVhSeWVXMUFaRzFwZEhKNWN5MX
    NZWEIwYjNBQkFnTUVCUVlICi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=
  type: Z2l0
  url: Z2l0QGdpdGh1Yi5jb206c2FyaXRhc2EtbmVzdC9kZXNrdG9wLmdpdA==
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: desktop
  namespace: argo-cd
type: Opaque
---
apiVersion: v1
data:
  name: ZnJvbnRlbmQ=
  project: ZGVmYXVsdA==
  sshPrivateKey: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdG
    RqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3Ra
    VwpReU5UVXhPUUFBQUNEbXJ2ek9PQVcvL1NpekNBdjJwTGlsZUFKNjNPdEZ3U3d6MEdSS0
    R5bDdpQUFBQUtCYXBneTZXcVlNCnVnQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDRG1ydnpP
    T0FXLy9TaXpDQXYycExpbGVBSjYzT3RGd1N3ejBHUktEeWw3aUEKQUFBRUJDUGNaazFQbU
    51eU5vRjJNOC9VanhoRzBtQURZNlNqSG9hbnovY1hodjllYXUvTTQ0QmIvOUtMTUlDL2Fr
    dUtWNApBbnJjNjBYQkxEUFFaRW9QS1h1SUFBQUFGbVJ0YVhSeWVXMUFaRzFwZEhKNWN5MX
    NZWEIwYjNBQkFnTUVCUVlICi0tLS0tRU5EIE9QRU5TU0ggUFJJVkFURSBLRVktLS0tLQo=
  type: Z2l0
  url: Z2l0QGdpdGh1Yi5jb206c2FyaXRhc2EtbmVzdC9mcm9udGVuZC5naXQ=
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: frontend
  namespace: argo-cd
type: Opaque
```

2023-03-29 04:38 UTC, kseniyashaydurova requested changes

2023-03-29 04:38 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +if [[ $# -eq 0 ]]; then
Please always add task link to your PRs (to save our time) - https://github.com/saritasa-nest/saritasa-devops-camp/blob/main/chapter2%20-%20bash%20basics/l1%20-%20bash%20basics.md#t2---generate-kustomizationyaml

2023-03-29 04:38 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +   echo args passed
Not clear message, please add more meaningful message here

2023-03-29 04:38 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +if [[ -d ${folder} ]]; then
Needs more comments above, that you remove existing `repos` folder and create a new one, by the way `rm -rf $dir` command doesn't raise error if folder doesn't exist, so you can avoid `id` condition and do just like this:
```
clean_workspace() {
    rm -rf ${folder} && mkdir ${folder}
}
```

It would look nicer

2023-03-29 04:38 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +# arg1 Name
```suggestion
# arg1 Repo name
```

2023-03-29 04:38 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +cat <<EOF > ${outputFilePath}
Add docs what you do here

2023-03-29 04:38 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +cat <<EOF
It is good practice to define vars with names in bash files, i.e.
```
local repo_name=$1
echo $repo_name
``` 

Then your code would be much easier for reading

2023-03-29 04:38 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +kubectl kustomize ${folder}
Basically script does what it needs to do, here are only beautifyings! Good job!

2023-03-29 04:41 UTC, dmitrymaslov13 commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +if [[ $# -eq 0 ]]; then
Yes thank you! I was just watching the last review and started adding, but you are a little ahead of me :D

2023-03-29 04:56 UTC, dmitrymaslov13 commented
@kseniyashaydurova Is there any generally accepted codestyle in the command for variable names, functions, and options for their declarations?

2023-03-30 08:11 UTC, kseniyashaydurova commented
> @kseniyashaydurova Is there any generally accepted codestyle in the command for variable names, functions, and options for their declarations?

@dmitrymaslov13 we would suggest you to follow this guide - https://google.github.io/styleguide/shellguide.html#s4-comments You can share it with a team or ask @dmitry-mightydevops maybe he has some other guide for you

2023-03-30 08:31 UTC, kseniyashaydurova requested changes

2023-03-30 08:31 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +  echo this script requires 1 or more arguments
I suggest to improve message to smth more clear:
```
echo "No arguments passed. You need to pass at least 1 argument to proceed with the script."
```

Also you can add `help` function to your bash script, so you could do `./script.sh -h` - https://opensource.com/article/19/12/help-bash-program

2023-03-30 08:31 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +cat <<EOF > ${outputFilePath}
Let's wrap this `cat` and `for` loop in separate function and call it `generate_kustomization_file`.

2023-03-30 08:31 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +get_secret_generator() {
```suggestion
generate_repo_secret() {
```

2023-04-03 03:30 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +readonly CONFIGURATION_NAMES=( "$@" )
I think this variable name may lead to misunderstanding, especially for people who reads this code for the first time and he doesn't know the task. So I would better call it `REPO_NAMES`

2023-04-03 03:30 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +local configuration_name="$1"
Why you have different indents here and in function above for example? Let's always have indent in 2 spaces.

2023-04-03 03:30 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +# Generate kustomiztion file.
Please check out this comments block on typos

2023-04-03 03:30 UTC, kseniyashaydurova commented on chapter2/tests/t2/chapter2-t2-gen-kustomization.sh
> +local repo_name=$1
Don't see that it is fixed

2023-04-03 08:00 UTC, roman-mightydevops requested changes
Please add a check that arguments are valid repo names, now I can generate broken manifests with the scripts:
```
➜ ./chapter2-t2-gen-kustomization.sh repo1 repo2 repo3 repo4 'repo 5'

➜ kustomize build repos | k apply -f -
+ kubectl apply -f -
secret/repo1 created
secret/repo2 created
secret/repo3 created
secret/repo4 created
The Secret "repo 5" is invalid: metadata.name: Invalid value: "repo 5": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

2023-04-13 02:50 UTC, kseniyashaydurova approved these changes

2023-04-26 06:25 UTC, roman-mightydevops approved these changes

2023-04-26 06:25 UTC, roman-mightydevops commented on chapter2/tests/t2/.gitignore
> +repos/*
Fix the warning please

2023-04-29 17:13 UTC, merged