feat: t4 - files no extensions
dmitrymaslov13/devops-camp-2023 pull request #6
Opened 2023-04-03 01:19 UTC by dmitrymaslov13

# Summary

## Test Task
Script should get a folder as an argument and return all files (including in the nested directories) but without the extension
name the file: chapter2-l2-t4-files-no-extensions.sh
example of the call:

`./chapter2-l2-t4-files-no-extensions.sh ~/tmp/bazel`
```sh
/tmp/bazel/tools/objc/dummy
/tmp/bazel/third_party/zlib/zutil
/tmp/bazel/third_party/zlib/uncompr
/tmp/bazel/third_party/zlib/trees
/tmp/bazel/third_party/zlib/test/minigzip
/tmp/bazel/third_party/zlib/test/infcover
/tmp/bazel/third_party/zlib/test/example
/tmp/bazel/third_party/zlib/inftrees
```
## my results
i create example dir:
```sh
example-dir
├── file.sh
├── file with spaces.sh
├── .gitignore
├── subdir
│   ├── file.sh
│   └── file with spaces.sh
└── subdir with spaces
```

```sh
❯ ./chapter2-l2-t4-files-no-extensions.sh example-dir 
```

**output**:
```sh
example-dir/file with spaces
example-dir/file
example-dir/subdir/file
example-dir/subdir/file with spaces
example-dir/
```

2023-04-03 01:21 UTC, dmitrymaslov13 commented
at the moment I am facing the problem that the file named `.gitignore` is not displayed correctly. WIP

2023-04-03 15:04 UTC, dmitrymaslov13 commented
I had to slightly increase the amount of code, but now files with a dot at the beginning are supported.

If I invented the wheel, I will be glad to get feedback and a tip on an alternative solution :D

2023-04-05 07:52 UTC, kseniyashaydurova requested changes

2023-04-05 07:52 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +#!/bin/bash
Please add description in comments of the script what problem it solves

2023-04-05 07:52 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +
Something doesn't work here:
![image](https://user-images.githubusercontent.com/26448672/230013298-beec2394-1913-476d-83b4-527dc36277a0.png)

2023-04-05 07:52 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +readonly FILES=( $( find "${DIRECTORY_PATH}" -type f ) )
Why double brackets here?

2023-04-05 07:52 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +# Get file name without extenstion
```suggestion
# Get file name without extension
```

2023-04-05 07:52 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +IFS=$'\n'
Strange output when no `dir` exists, I mean last string with `/`
![image](https://user-images.githubusercontent.com/26448672/230014070-dcf1d6db-524f-4b05-8250-f355dab99712.png)

2023-04-05 07:52 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +  local file_dir="$( get_path_to_file_dir "${file_path}" )"
I suggest to not use quotes `"` for such expressions with `$()`

2023-04-05 07:52 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +get_file_name_without_extenstion() {
That looks rather magically from the first sight and seems that it doesn't work correctly. Please try another way to remove extension in a file, consider `sed` command for example, it will be more clear

![image](https://user-images.githubusercontent.com/26448672/230015579-ddfe1b90-f02d-4b3e-a322-06b58063b674.png)

2023-04-05 07:52 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +  local file_name_without_first_symbol="${file_name: 1 : ${#file_name} }"
Why do you need to remove `first` symbol? What was the idea?

2023-04-05 07:52 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +  local file_name="$( get_file_name "${file_path}" )"
Also I think this code looks too complicated and can be much easier, i.e. I don't see any sense in splitting file's path to `path` and `filename` and combine them later again. Let's try to find simpler solution to avoid these manipulations.

2023-04-05 08:01 UTC, kseniyashaydurova requested changes

2023-04-05 08:01 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +#!/bin/bash
Please also consider this case:
![image](https://user-images.githubusercontent.com/26448672/230018911-a399a09a-04a0-4b03-aedb-87f31dc741f1.png)


I suppose that there should be output:
```
test/.test/
test/.test/1
test/.test/2
test/
test/1
test/2
```

2023-04-05 08:04 UTC, dmitrymaslov13 commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +  local file_name_without_first_symbol="${file_name: 1 : ${#file_name} }"
due to the fact that the name of the file in Linux can begin with a dot
for example: `.gitignore`

2023-04-09 09:00 UTC, dmitrymaslov13 commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +readonly FILES=( $( find "${DIRECTORY_PATH}" -type f ) )
the idea was to make an array from the search result

2023-04-13 02:57 UTC, kseniyashaydurova approved these changes

2023-04-13 02:57 UTC, kseniyashaydurova commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +done
Please always add one empty line at the end of each script

2023-04-26 07:29 UTC, roman-mightydevops approved these changes

2023-04-26 07:29 UTC, roman-mightydevops commented on chapter2/tests/t4/chapter2-l2-t4-files-no-extensions.sh
> +readonly FILE_PATHES=$(find "${DIRECTORY_PATH}" -type f)
Just FYI
https://unix.stackexchange.com/a/687856

2023-04-29 17:26 UTC, merged