feat: T5  - get file unique extensions
dmitrymaslov13/devops-camp-2023 pull request #8
Opened 2023-04-03 17:23 UTC by dmitrymaslov13

# Summary

## Test Task
Script should get a folder as an argument and return a list of unique extensions of all files (including in the nested directories)
**name the file:** `chapter2-l2-t5-get-file-unique-extensions.sh`
**example of the call:**
```sh
./chapter2-l2-t5-get-file-unique-extensions.sh ~/tmp/bazel
c
h
zip
```
## my results
Folder from example:
```sh
/home/dmitrym/Documents/Saritasa/devops-camp-2023
├── chapter2
│   └── tests
│       ├── t1
│       ├── t2
│       ├── t4
│       └── t5
│           └── chapter2-l2-t5-get-file-unique-extensions.sh
├── .git
│   └── ...
├── .github
│   ├── CODEOWNERS
│   └── workflows
└── README.md
```

```sh
❯ ./chapter2-l2-t5-get-file-unique-extensions.sh $SARITASA/devops-camp-2023 
```

**output**:
```sh
sample
md
sh
```

2023-04-05 08:46 UTC, kseniyashaydurova requested changes

2023-04-05 08:46 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +readonly FILE_PATHES=( $( find "${DIRECTORY_PATH}" -type f ) )
Why double brackets here? Let's not do like this

2023-04-05 08:46 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +# Get file name without extenstion
You have everywhere this typo

```suggestion
# Get file name without extension
```

2023-04-05 08:46 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +  if [[ "${file_name: 0 : 1 }" != "." && ${file_name} == *.*  ]]; then
I found a bug :)
![image](https://user-images.githubusercontent.com/26448672/230029283-3e2e7368-04f3-4f2c-94f2-b8a3aa0af530.png)

2023-04-05 08:46 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +(
Can you do the same without brackets here?

2023-04-09 08:58 UTC, dmitrymaslov13 commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +  if [[ "${file_name: 0 : 1 }" != "." && ${file_name} == *.*  ]]; then
We discussed this case with Ksenia, and came to the conclusion that the dotfile is not a file extenstion

2023-04-13 03:37 UTC, kseniyashaydurova requested changes

2023-04-13 03:37 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +
too many empty lines at the end :)

2023-04-13 03:37 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +#!/bin/bash
Doesn't look like it works correctly, now it prints not only extensions
![image](https://user-images.githubusercontent.com/26448672/231642644-7f3e09ea-dbc2-4064-ae70-a2a59342a1ee.png)

2023-04-13 03:38 UTC, dmitrymaslov13 commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +#!/bin/bash
Ops!) Thank you

2023-04-14 03:36 UTC, kseniyashaydurova requested changes

2023-04-14 03:36 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +#!/bin/bash
We still have some problems here :smiling_face_with_tear:

![image](https://user-images.githubusercontent.com/26448672/231935051-1edb2229-c75d-4a8a-9f02-09e58d9b6977.png)

2023-05-03 03:13 UTC, kseniyashaydurova approved these changes
Please add small fixes

2023-05-03 03:13 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +get_file_extenstion() {
```suggestion
get_file_extension() {
```

2023-05-03 03:13 UTC, kseniyashaydurova commented on chapter2/tests/t5/chapter2-l2-t5-get-file-unique-extensions.sh
> +  if [[ "${file_name}" != *.* ]]; then
Please add comment related to each `if` condition, so it would be clear what happens here

2023-12-09 22:07 UTC, closed without merging